version: "3"

services:
  api:
    build: 
      context: ./server
    command: sh -c "npm install && npm install -g knex && npm run migrate:run && npm run seed && npm run dev"
    ports:
      - "3333:3333"
    volumes: 
      - ./server:/usr/app
    links:
      - db
    depends_on: 
      - db
    environment: 
      HOST: http://localhost
      PORT: 3333
      TOKEN_ADMIN_SECRET: 3AFFYhIGecpkPsKkTSKoCpvi91BpupSO
      TZ: America/Sao_Paulo
      DB_DRIVER: pg
      DB_HOST: db
      DB_USER: docker
      DB_PASSWORD: postgres
      DB_DATABASE: plathanus_db
  web-adm:
    stdin_open: true
    build: 
      context: ./web-adm
    volumes:
      - /app/node_modules
      - ./web-adm:/usr/app
    ports:
      - "3001:3000"
    environment: 
      REACT_APP_API_URL: http://localhost:3333
      REACT_APP_PUBLIC_URL: http://localhost:3001
  web:
    stdin_open: true
    build: 
      context: ./web
    volumes:
      - /app/node_modules
      - ./web:/usr/app
    ports:
      - "3000:3000"
    environment: 
      REACT_APP_API_URL: http://localhost:3333
      REACT_APP_PUBLIC_URL: http://localhost:3000
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=plathanus_db